version: '3.3'
services:
  front:
    image: harunari/financial_analysis_frontend:stable
    container_name: frontend-server
    ports:
     - "80"
  api:
    image: harunari/financial_analysis_api:stable
    container_name: analysis_api
    environment:
      DB_SERVERNAME: report_rdb_primary
      DB_USERID: postgres
      DB_NAME: postgres
      DB_PORT: 5432
      DB_PASSWORD: mysecretpassword
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Development
    ports:
     - "80"
    depends_on:
      - rdb_primary
      - aquire_financial_reports_batch
  rdb_primary:
    image: harunari/financial_report_primary_database:stable
    container_name: report-rdb-primary
    volumes:
      - primary_database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: mysecretpassword
    expose:
      - 5432
  import_corporation_info_batch:
    image: harunari/import_corporation_info_batch:stable
    environment:
      DB_SERVERNAME: report_rdb_primary
      DB_USERID: postgres
      DB_NAME: postgres
      DB_PORT: 5432
      DB_PASSWORD: mysecretpassword
    depends_on:
      - rdb_primary
  aquire_financial_reports_batch:
    image: harunari/aquire_financial_reports_batch:stable
    container_name: aquire-financial-reports-batch
    environment:
      DB_SERVERNAME: report_rdb_primary
      DB_USERID: postgres
      DB_NAME: postgres
      DB_PORT: 5432
      DB_PASSWORD: mysecretpassword
    depends_on:
      - rdb_primary
      - aquire_account_items_batch
      - import_corporation_info_batch
  aquire_account_items_batch:
    image: harunari/aquire_account_items_batch:stable
    environment:
      DB_SERVERNAME: report_rdb_primary
      DB_USERID: postgres
      DB_NAME: postgres
      DB_PORT: 5432
      DB_PASSWORD: mysecretpassword
    depends_on:
      - rdb_primary
