apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: auto-trade-storage
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  location: japaneast
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auto-trade-storage
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: auto-trade-storage
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rdb-primary-deployment
  labels:
    app: rdb-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rdb-primary
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rdb-primary
    spec:
      containers:
        - env:
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_PASSWORD
            value: mysecretpassword
          - name: POSTGRES_USER
            value: postgres
          image: harunari/financial_report_primary_database:stable
          name: rdb-primary
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: primary-database
              subPath: postgres
      restartPolicy: Always
      volumes:
      - name: primary-database
        persistentVolumeClaim:
          claimName: auto-trade-storage
status: {}