apiVersion: batch/v1
kind: Job
metadata:
  name: import-corporation-info
spec:
  backoffLimit: 6
  completions: 1
  template:
    spec:
      containers:
        - env:
            - name: DB_NAME
              value: postgres
            - name: DB_PASSWORD
              value: mysecretpassword
            - name: DB_PORT
              value: "5432"
            - name: DB_SERVERNAME
              value: rdb-primary
            - name: DB_USERID
              value: postgres
          image: harunari/import_corporation_info_batch:stable
          name: import-corporation-info
      restartPolicy: OnFailure