apiVersion: batch/v1
kind: Job
metadata:
  name: acquire-financial-report-recovery-20220629
  namespace: research-xbrl
spec:
  backoffLimit: 6
  completions: 1
  template:
    spec:
      containers:
      - name: acquire-financial-report
        image: harunari/aquire_financial_reports_batch:stable-468
        command: ["dotnet", "/app/AquireFinancialReports.dll", "--from", "2020-3-4", "--to", "2022-5-11", "--max-parallelism", "2"]
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: research-xbrl-secret
              key: rdb-primary-db-name
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: research-xbrl-secret
              key: rdb-primary-password
        - name: DB_PORT
          value: "5432"
        - name: DB_SERVERNAME
          valueFrom:
            secretKeyRef:
              name: research-xbrl-secret
              key: rdb-primary-server-name
        - name: DB_USERID
          valueFrom:
            secretKeyRef:
              name: research-xbrl-secret
              key: rdb-primary-user
      restartPolicy: OnFailure