apiVersion: batch/v1
kind: Job
metadata:
  name: import-corporation-info
  namespace: research-xbrl
spec:
  backoffLimit: 6
  completions: 1
  template:
    spec:
      containers:
        - name: import-corporation-info
          image: harunari/import_corporation_info_batch:stable-431
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: research-xbrl-secret
                  key: rdb-primary-db-name
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: research-xbrl-secret
                  key: rdb-primary-password
            - name: DB_PORT
              value: "5432"
            - name: DB_SERVERNAME
              valueFrom:
                secretKeyRef:
                  name: research-xbrl-secret
                  key: rdb-primary-server-name
            - name: DB_USERID
              valueFrom:
                secretKeyRef:
                  name: research-xbrl-secret
                  key: rdb-primary-user
      restartPolicy: OnFailure