apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api
    spec:
      containers:
        - name: analysis-api
          image: harunari/financial_analysis_api:stable-431
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: ASPNETCORE_URLS
            value: http://+:80
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: rdb-primary-secret
                key: rdb-primary-db-name
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rdb-primary-secret
                key: rdb-primary-password
          - name: DB_PORT
            value: "5432"
          - name: DB_SERVERNAME
            valueFrom:
              secretKeyRef:
                name: rdb-primary-secret
                key: rdb-primary-server-name
          - name: DB_USERID
            valueFrom:
              secretKeyRef:
                name: rdb-primary-secret
                key: rdb-primary-user
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
      restartPolicy: Always
status: {}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  targetCPUUtilizationPercentage: 50